=== JohanAndres19/Tendencias-XSD/schemabibloteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref ="Explorador"/>
                <xs:element ref ="SuperColeccion" minOccurs="0"/>
                <xs:element ref ="Coleccion" minOccurs="0"/>
                <xs:element ref ="Item" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Explorador">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Buscador" type="xs:string"/>
                <xs:element ref="Filtro"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Filtro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="etiqueta" type="xs:string"   maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>            
    </xs:element>

    <xs:element name = "SuperColeccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Coleccion" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name = "Coleccion">
        <xs:complexType>
            <xs:sequence>
            <xs:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Item">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nombre" type="xs:string"/>
                <xs:element name="Descripcion" type="xs:string"/>
                <xs:element name="Fecha" type="xs:date"/>            
                <xs:element name="Categoria">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Etiqueta1" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:any minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JohanAndres19/Tendencias-XSD/bibloteca.xml
<?xml version="1.0" encoding="UTF-8"?>

<Catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="schemabibloteca.xsd"
>
   <Explorador>
      <Buscador></Buscador>
      <Filtro>
         <etiqueta>suspenso</etiqueta>
         <etiqueta>terror</etiqueta>
         <etiqueta>psicologico</etiqueta>
      </Filtro>
   </Explorador>
   <Item>
      <Nombre>Fragmentado</Nombre>
      <Descripcion>Pelicula que .....</Descripcion>
      <Fecha>2002-09-24</Fecha>
      <Categoria>
         <Etiqueta1></Etiqueta1>
      </Categoria>
   </Item>
</Catalogo>
